### PR TITLE
Gradle support, automatic jar building

### PR DESCRIPTION
**Pull request by SirEdvin**
For issue #6

### CODE REVIEW

**Comment by Armaxis** [comment]
Does it still work if launching from Eclipse without Gradle?

**Comment by SirEdvin** [comment]
Maybe, if libraries was added

**Comment by Armaxis** [comment]
Can you please test it first? I don't want to break existing build for non-gradle users.

**Comment by SirEdvin** [comment]
It works on Eclipse 3.8.1 (I import project from GitHub with EGit and add library JUnit 4. After this, I build project without errors).

**Comment by drbignik** [comment]
+1 on this. I don't use Eclipse, but instead IntelliJ IDEA, and I also want to build this project.

**Comment by Armaxis** [comment]
Aight, merged into master. Happy New Year, by the way :)

**Comment by SirEdvin** [comment]
Happy New Year! :)

**Pull request merged**
